# Generated by Django 3.2.9 on 2021-11-26 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
