# Generated by Django 4.0 on 2022-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211201_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short',
            field=models.TextField(max_length=90),
        ),
    ]
