# Generated by Django 4.0 on 2022-01-12 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_calendar_options_remove_calendar_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите имя')),
                ('phone', models.CharField(max_length=70, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=2000, verbose_name='Комментарий или вопрос')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('choice_Rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendar')),
            ],
            options={
                'verbose_name': 'Запись к событию',
                'verbose_name_plural': 'Записи к событиям',
                'ordering': ['-time_create', 'name'],
            },
        ),
    ]
