# Generated by Django 4.0 on 2022-01-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_calendar_title_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='choice_Rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cобытие', to='main.calendar'),
        ),
    ]
