# Generated by Django 4.0 on 2022-01-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_record_choice_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='choice_Rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendar', verbose_name='Cобытие'),
        ),
    ]
